[font]
size = 10.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "mononoki Nerd Font"
style = "Regular"

[window]
opacity = 0.8

[window.padding]
x = 3
y = 3
