autocmd VimEnter * echo 'Welcome back to vim, Kien!'

set number numberwidth=3
syntax on

let mapleader = ","
let maplocalleader = "\\"

" File fuzzy funder + selection menu

set path+=**

" Highlight character when line is longer than 90 characters

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%90v', 100)

" Some custom mappings to save time

" NORMAL MODE

" Command to open NERDTree

nnoremap <leader>nt :NERDTree<CR>

" Opens .vimrc file in a new vertical split

" [E]dit [V]imrc
nnoremap <leader>ev :vsplit ~/.vim/vimrc<cr>
" [S]ource [V]imrc
nnoremap <leader>sv :source ~/.vim/vimrc<cr>

" Puts double quotes around current word

" nnoremap <leader>" viw<esc>a"<esc>bi"<esc>lel
" nnoremap <leader>' viw<esc>a'<esc>bi'<esc>lel

" Puts the appropriate parenthesis around visual selection

" vnoremap <leader>( <esc>`>a)<esc>`<i(<esc>
" vnoremap <leader>" <esc>`>a"<esc>`<i"<esc>

" INSERT MODE

" Ctrl+p to insert empty line below

inoremap <c-p> <esc>A<enter><esc>ki

" Indentation settings

set tabstop=4
set softtabstop=0
set expandtab
set shiftwidth=4
set smarttab


" OPERATOR MOVEMENTS

" p as movement to target anything inside the [P]arenthesis the cursor is in

onoremap p i(

" np as movement to target anything inside the [N]ext set of [Parenthesis]

onoremap np :<c-u>normal! f(vi(<cr>

" HARDCORE MODE BITCH 

inoremap jk <esc>
inoremap <esc> <nop>

noremap <up> <nop>
noremap <down> <nop>
noremap <left> <nop>
noremap <right> <nop>

" The following lines are needed since even while nop-ed, arrows write
" characters such as "OAOBOCOD" when pressed in insert mode
nnoremap <silent> <ESC>OA <nop>
nnoremap <silent> <ESC>OB <nop>
nnoremap <silent> <ESC>OC <nop>
nnoremap <silent> <ESC>OD <nop>
inoremap <silent> <ESC>OA <nop>
inoremap <silent> <ESC>OB <nop>
inoremap <silent> <ESC>OC <nop>
inoremap <silent> <ESC>OD <nop>

" Options for splits
set splitbelow
set splitright

" Fast movement through splits
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Fold options

set foldmethod=indent
augroup OpenAllFoldsOnFileOpen
	autocmd!
	autocmd BufRead * normal zR
augroup END

" Relative Numbering

:set number relativenumber

:augroup numbertoggle
:  autocmd!
:  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
:  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
:augroup END

" ABBREVIATIONS

iabbrev @@ kientuong@gmail.com

let g:python3_host_prog = '/usr/bin/python'

let g:C_UseTool_cmake = 'yes'
let g:C_UseTool_doxygen = 'yes'
filetype plugin on

" Python PEP8 Indentation rules

au BufNewFile, BufRead *.py
	\ set tabstop=4
	\ set softtabstop=4
	\ set shiftwidth=4
	\ set textwidth=79
	\ set expandtab
	\ set autoindent
	\ set fileformat=unix

" Python mark extra whitespace

au BufRead, BufNewFile *.py, *.piw, *.c, *.h match BadWhiteSpace /\s\+$/

" Python highlight

let python_highlight_all=1

" HTML, JS, CSS Indentation Rules

au BufNewFile, BufRead *.js, *.html, *.css
	\ set tabstop=2
	\ set softtabstop=2
	\ set shiftwidth=2

au BufNewFile, BufRead *.vhd
	\ set tabstop=4
	\ set softtabstop=0
	\ set expandtab
	\ set shiftwidth=4
	\ set smarttab

" CoC settings

" Use tab for trigger completion with characters ahead and navigate.
inoremap <silent><expr> <TAB>
      \ pumvisible() ? "\<C-n>" :
      \ <SID>check_back_space() ? "\<TAB>" :
      \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

" Make <CR> auto-select the first completion item and notify coc.nvim to
" format on enter, <cr> could be remapped by other vim plugin
inoremap <silent><expr> <cr> pumvisible() ? coc#_select_confirm()
                              \: "\<C-g>u\<CR>\<c-r>=coc#on_enter()\<CR>"

" Use `[g` and `]g` to navigate diagnostics
" Use `:CocDiagnostics` to get all diagnostics of current buffer in location list.
nmap <silent> [g <Plug>(coc-diagnostic-prev)
nmap <silent> ]g <Plug>(coc-diagnostic-next)

" GoTo code navigation.
nmap <silent> gd <Plug>(coc-definition)
nmap <silent> gy <Plug>(coc-type-definition)
nmap <silent> gi <Plug>(coc-implementation)
nmap <silent> gr <Plug>(coc-references)

" Use K to show documentation in preview window.
nnoremap <silent> K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction

" Highlight the symbol and its references when holding the cursor.
autocmd CursorHold * silent call CocActionAsync('highlight')

" Symbol renaming.
nmap <leader>rn <Plug>(coc-rename)

" Formatting selected code.
xmap <leader>f  <Plug>(coc-format-selected)
nmap <leader>f  <Plug>(coc-format-selected)

augroup mygroup
  autocmd!
  " Setup formatexpr specified filetype(s).
  autocmd FileType typescript,json setl formatexpr=CocAction('formatSelected')
  " Update signature help on jump placeholder.
  autocmd User CocJumpPlaceholder call CocActionAsync('showSignatureHelp')
augroup end

" Applying codeAction to the selected region.
" Example: `<leader>aap` for current paragraph
xmap <leader>a  <Plug>(coc-codeaction-selected)
nmap <leader>a  <Plug>(coc-codeaction-selected)

" Remap keys for applying codeAction to the current buffer.
nmap <leader>ac  <Plug>(coc-codeaction)
" Apply AutoFix to problem on the current line.
nmap <leader>qf  <Plug>(coc-fix-current)

" Map function and class text objects
" NOTE: Requires 'textDocument.documentSymbol' support from the language server.
xmap if <Plug>(coc-funcobj-i)
omap if <Plug>(coc-funcobj-i)
xmap af <Plug>(coc-funcobj-a)
omap af <Plug>(coc-funcobj-a)
xmap ic <Plug>(coc-classobj-i)
omap ic <Plug>(coc-classobj-i)
xmap ac <Plug>(coc-classobj-a)
omap ac <Plug>(coc-classobj-a)

" Use CTRL-S for selections ranges.
" Requires 'textDocument/selectionRange' support of LS, ex: coc-tsserver
nmap <silent> <C-s> <Plug>(coc-range-select)
xmap <silent> <C-s> <Plug>(coc-range-select)

" Add `:Format` command to format current buffer.
command! -nargs=0 Format :call CocAction('format')

" Add `:Fold` command to fold current buffer.
command! -nargs=? Fold :call     CocAction('fold', <f-args>)

" Add `:OR` command for organize imports of the current buffer.
command! -nargs=0 OR   :call     CocAction('runCommand', 'editor.action.organizeImport')

" Add (Neo)Vim's native statusline support.
" NOTE: Please see `:h coc-status` for integrations with external plugins that
" provide custom statusline: lightline.vim, vim-airline.
set statusline^=%{coc#status()}%{get(b:,'coc_current_function','')}

" Mappings for CoCList
" Show all diagnostics.
nnoremap <silent><nowait> <space>a  :<C-u>CocList diagnostics<cr>
" Manage extensions.
nnoremap <silent><nowait> <space>e  :<C-u>CocList extensions<cr>
" Show commands.
nnoremap <silent><nowait> <space>c  :<C-u>CocList commands<cr>
" Find symbol of current document.
nnoremap <silent><nowait> <space>o  :<C-u>CocList outline<cr>
" Search workspace symbols.
nnoremap <silent><nowait> <space>s  :<C-u>CocList -I symbols<cr>
" Do default action for next item.
nnoremap <silent><nowait> <space>j  :<C-u>CocNext<CR>
" Do default action for previous item.
nnoremap <silent><nowait> <space>k  :<C-u>CocPrev<CR>
" Resume latest coc list.
nnoremap <silent><nowait> <space>p  :<C-u>CocListResume<CR>

" haskell-vim settings

let g:haskell_enable_quantification = 1   " to enable highlighting of `forall`
let g:haskell_enable_recursivedo = 1      " to enable highlighting of `mdo` and `rec`
let g:haskell_enable_arrowsyntax = 1      " to enable highlighting of `proc`
let g:haskell_enable_pattern_synonyms = 1 " to enable highlighting of `pattern`
let g:haskell_enable_typeroles = 1        " to enable highlighting of type roles
let g:haskell_enable_static_pointers = 1  " to enable highlighting of `static`
let g:haskell_backpack = 1                " to enable highlighting of backpack keywords
let g:haskell_indent_if = 3

" vim-go settings

let g:go_highlight_structs = 1 
let g:go_highlight_methods = 1
let g:go_highlight_functions = 1
let g:go_highlight_operators = 1
let g:go_highlight_build_constraints = 1

" instant-markdown settings

"Uncomment to override defaults:
"let g:instant_markdown_slow = 1
let g:instant_markdown_autostart = 0
"let g:instant_markdown_open_to_the_world = 1
"let g:instant_markdown_allow_unsafe_content = 1
"let g:instant_markdown_allow_external_content = 0
let g:instant_markdown_mathjax = 1
"let g:instant_markdown_logfile = '/tmp/instant_markdown.log'
"let g:instant_markdown_autoscroll = 0
"let g:instant_markdown_port = 8888
"let g:instant_markdown_python = 1

" md-img-paste settings

autocmd FileType markdown nmap <silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>

" elm compilation settings

autocmd FileType elm nnoremap <leader>b !elm make Main.elm --output=../elm.js

" there are some defaults for image directory and image name, you can change them
" let g:mdip_imgdir = 'img'
" let g:mdip_imgname = 'image'
" vim-plug automatic installation

" FastFold settings

nmap zuz <Plug>(FastFoldUpdate)
let g:fastfold_savehook = 1
let g:fastfold_fold_command_suffixes =  ['x','X','a','A','o','O','c','C']
let g:fastfold_fold_movement_commands = [']z', '[z', 'zj', 'zk']

"let g:markdown_folding = 1
let g:python_folding = 1

let g:elm_setup_keybindings = 0

" vimtext config

" let g:tex_flavor = 'xetex'
let g:vimtex_view_general_viewer = 'okular'
let g:vimtex_compiler_method = 'tectonic'
"
" filenames like *.xml, *.html, *.xhtml, ...
" These are the file extensions where this plugin is enabled.
"
let g:closetag_filenames = '*.html,*.xhtml,*.phtml,*.tsx,*.ts'

" filenames like *.xml, *.xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filenames = '*.xhtml,*.jsx,*.tsx,*.ts'

" filetypes like xml, html, xhtml, ...
" These are the file types where this plugin is enabled.
"
let g:closetag_filetypes = 'html,xhtml,phtml,tsx,ts'

" filetypes like xml, xhtml, ...
" This will make the list of non-closing tags self-closing in the specified files.
"
let g:closetag_xhtml_filetypes = 'xhtml,jsx,tsx,ts'

" integer value [0|1]
" This will make the list of non-closing tags case-sensitive (e.g. `<Link>` will be closed while `<link>` won't.)
"
let g:closetag_emptyTags_caseSensitive = 1

" dict
" Disables auto-close if not in a "valid" region (based on filetype)
"
let g:closetag_regions = {
    \ 'typescript.tsx': 'jsxRegion,tsxRegion',
    \ 'javascript.jsx': 'jsxRegion',
    \ 'typescriptreact': 'jsxRegion,tsxRegion',
    \ 'javascriptreact': 'jsxRegion',
    \ }

" Shortcut for closing tags, default is '>'
"
let g:closetag_shortcut = '>'

" Add > at current position without closing the current tag, default is ''
"
let g:closetag_close_shortcut = '<leader>>'

" Activate vim server
if empty(v:servername) && exists('*remote_startserver')
      call remote_startserver('VIM')
endif

" Plug autoinstall

if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

" vim-plug stuff

call plug#begin('~/.vim/plugged')
" Aesthetics
Plug 'sickill/vim-monokai'
Plug 'vim-airline/vim-airline-themes'
Plug 'https://github.com/vim-airline/vim-airline.git'
Plug 'numirias/semshi', {'do': ':UpdateRemotePlugins'}
Plug 'styled-components/vim-styled-components' 

" Functionality
Plug 'https://github.com/scrooloose/nerdtree.git'
Plug 'https://github.com/apalmer1377/factorus'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" Plug 'jiangmiao/auto-pairs'
" Plug 'tpope/vim-endwise'
Plug 'tpope/vim-surround'
Plug 'alvan/vim-closetag'


" Linters and Formatters
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'godlygeek/tabular'
Plug 'vim-scripts/indentpython.vim'
Plug 'maksimr/vim-jsbeautify'

" Language Addons
Plug 'plasticboy/vim-markdown'
Plug 'lervag/vimtex'
Plug 'jeetsukumaran/vim-pythonsense'
Plug 'cespare/vim-toml'
Plug 'mattn/emmet-vim'
Plug 'pangloss/vim-javascript'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'fatih/vim-go'
Plug 'petRUShka/vim-sage'

" Other stuff
Plug 'suan/vim-instant-markdown', {'for': 'markdown'}
Plug 'ferrine/md-img-paste.vim'
Plug 'Konfekt/FastFold'
call plug#end()

" graphic settings

colorscheme monokai
hi! Normal ctermbg=NONE guibg=NONE
let g:airline_powerline_fonts = 1

" Various

set wrap
set nocompatible
